version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./local-storage:/app/local-storage
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - LLAMA_CLOUD_ORG_ID=${LLAMA_CLOUD_ORG_ID}

  # Development tools
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" 